// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyCpqQwPmMIoNmACZOaqatzGLXMBQMo3E',
    appId: '1:215062066311:web:863cd152c9564e48447422',
    messagingSenderId: '215062066311',
    projectId: 'login-page-dbd82',
    authDomain: 'login-page-dbd82.firebaseapp.com',
    storageBucket: 'login-page-dbd82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJ7Yd7QNlrdPYONIJpBliOzrrWoYBz9w',
    appId: '1:215062066311:android:afd06b5a334f84cb447422',
    messagingSenderId: '215062066311',
    projectId: 'login-page-dbd82',
    storageBucket: 'login-page-dbd82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK9hq_-H-GEAe7b7YnnbPQcXtlrjBt-Gk',
    appId: '1:215062066311:ios:4f3ae4f3b75dac54447422',
    messagingSenderId: '215062066311',
    projectId: 'login-page-dbd82',
    storageBucket: 'login-page-dbd82.firebasestorage.app',
    iosBundleId: 'com.example.tajory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK9hq_-H-GEAe7b7YnnbPQcXtlrjBt-Gk',
    appId: '1:215062066311:ios:4f3ae4f3b75dac54447422',
    messagingSenderId: '215062066311',
    projectId: 'login-page-dbd82',
    storageBucket: 'login-page-dbd82.firebasestorage.app',
    iosBundleId: 'com.example.tajory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyCpqQwPmMIoNmACZOaqatzGLXMBQMo3E',
    appId: '1:215062066311:web:e1c5ecd14800315b447422',
    messagingSenderId: '215062066311',
    projectId: 'login-page-dbd82',
    authDomain: 'login-page-dbd82.firebaseapp.com',
    storageBucket: 'login-page-dbd82.firebasestorage.app',
  );

}